### ISSUE TITLE
Week 1: Research, Environment Setup, First Commit

### ISSUE THREAD

**Issue by adilanchian** [TeamMoodGitHub/Mark-Term-1#1]
Your first week will be focused on getting your feet wet in mobile development as well as setting up a Github flow. For your project we will be utilizing API's and backend calculations heavily. As you get through each task go ahead and update this ticket so I can keep track of your progress! By the end of this week you should have:

- [x] Pulled down your Github Repository to begin working locally
- [x] Created a branch off of master named `week-one`
- [x] Updated READMED and committed any changes you see fit
- [x] Researched React Native / Node.js and be familiar with it
- [x] Created a "Hello World" React Native app that runs on Android ( I can test on iOS)
- [x] Researched what APIs you will be leveraging for campus maps, pins, etc.
- [ ] Created a simple Node.js server that you can launch locally
- [ ] Created a skeleton for how you want your mobile app to look
- [x] Commit all code to your local branch `week-one` and push it to remote

These tasks should give you a pretty nice understand what you are working with and should give you a strong foundation for the rest of your project! Don't forget you have a plethora of resources that you can utilize if you feel stuck.

Good luck, have fun, and  believe in you!

**Comment by adilanchian** [comment]
Mark, AWESOME job thus far man. I was able to use Expo App to get the build you made on my phone. Really cool way to get it started. 

I know you still have some node.js work to do as well as some skeleton work to do. We will go ahead and bring this over into week 2

**Comment by adilanchian** [comment]
I went a head and created your Week 2 issue on Github sir. Will close this issue now.

**Comment by mark-beshara** [comment]
Hey thanks man, glad that the build worked with expo for you too. I still wanna test the native version thats on the alt branch and see if it works.
