### ISSUE TITLE
Week 2: Node.js exploration, Create skeleton, and Enable 3rd Party Libraries

### ISSUE THREAD

**Issue by adilanchian** [TeamMoodGitHub/Mark-Term-1#2]
Fantastic work on this past week my man. It was really awesome to see you be able to see your Hello World app running natively on my phone. I want to now take your work a little further and to allow your app to have a more feature rich UI. This would I would like you to do the following:

- [x] Merge branch `week-one` into master 
- [x] Create a new branch off of master named `week-two`
- [x] Try to get the 3rd party libraries you needed working. If you do, merge `week-one-alt` into `week-two`
- [ ] Start laying out the UI for your app within React Native
- [ ] Create a local node.js server that you are able to access from your phone

I think these are some pretty solid tasks. Im very interested to see how you come up with the UI. Keep up the awesome work and please make sure to update this ticket as you complete tasks. I would love to see your comments when approaching issues. Thanks man!

**Comment by mark-beshara** [comment]
Merged week-one into master and then created the new branch. Also started working on a quick UI sketch on paper but will code it later in the week. Still looking into databases as well as what third party libraries I need.

**Comment by adilanchian** [comment]
Mark,

Killer work this week on your tasks and research. Im glad you were able to get a bit of work done even with all the stuff going on! 

Im going to close this issue on the contingency that these tasks from week two will move to week three. Awesome work my dude!
