### ISSUE TITLE
Week 3: Create Map View, Setup Local Node Server That Uses Mongodb

### ISSUE THREAD

**Issue by adilanchian** [TeamMoodGitHub/Mark-Term-1#3]
W E E K 3 - Damn, we are getting close!

As per our standup call, I want you to work on a couple tasks this week. To reiterate again as well, I am laying out the general path that I believe you should take to keep going on this project. If you feel you may want to go a different route or do things differently, just let me know and we will realign the tasks! For this week I would like you to do the following:

- [x] Create a branch off of `master` called `week-three`
- [x] Implement a map view in your app (I remember you were thinking about something from Airbnb?)
- [ ] Setup a node server that you are able to make requests to from your mobile device
- [ ] Setup a local mongodb database
- [ ] To bring it all full circle, grab your current location, and store it inside your mongodb database

After this week you will be nearly complete with the base of your project! Keep up the awesome work and don't forget to update this issue to keep track of your progress :)

**Comment by mark-beshara** [comment]
Latest commit has the map added to the project, as well as a marker to indicate user position, will create week-three branch now and continue to work off of it.

**Comment by adilanchian** [comment]
Im loving the progress you have been making on your project dude! Really pushing through. From what we talked about, you see, to have completed most of your tasks just missing a few! They will roll over to week 4 my friend! Great job
