### ISSUE TITLE
Week 4: Store Data in DB, Setup UI, Research Account Creation

### ISSUE THREAD

**Issue by adilanchian** [TeamMoodGitHub/Mark-Term-1#4]
W E E K 4 - HALF WAY DONE LESSS GOOOO BOIIII

I am laying out the general path that I believe you should take to keep going on this project. If you feel you may want to go a different route or do things differently, just let me know and we will realign the tasks! For this week I would like you to do the following:

- [x] Merge branch `week-three` into `master`
- [x] Create a branch off of master called `week-four`
- [ ] Grab your current location, and store it inside your mongodb database
- [ ] Create your initial UI (This can be quick and dirty)
- [x] Think about how you are going to want to have a user create an account (Hint: Social media maybe?)

After this week your project should be really coming to life and almost in an MVP (most viable product) state :) Keep up the great work my man and let me know if you need anything!

**Comment by mark-beshara** [comment]
Started working with firebase authentication and looked into how to integrate that into the app. Also restructured files and began routing from a simple login screen with no real functionality other than a button to move into mapview.

**Comment by mark-beshara** [comment]
Next week want to implement login -> Mapview routing, then add authorizations to login screen, and finally add markers to map view with up down vote keys and text description of event.

**Comment by adilanchian** [comment]
Hey Mark,

Thanks for the update my dude! Will go ahead and create a Week 6 ticket for ya:)
